---
name: Build Image

on:
  workflow_call:
    inputs:
      target:
        description: Build target
        default: frankenphp_prod
        type: string
        required: false

env:
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup workflow vars
        shell: bash
        run: |
          date_version=$(date +'%Y%m%d%H%M%S')
          docker_version="${{ github.ref_name }}-${date_version}"

          echo "version=${docker_version}" >> $GITHUB_OUTPUT

      - name: Setup GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container testing image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: ${{ inputs.target }}
          platforms: linux/amd64
          load: true
          push: false
          tags: ${{ env.IMAGE_PREFIX }}:testingz
          cache-from: type=gha
          cache-to: type=gha,mode=max
