---
name: PHPUnit

on:
  workflow_call:
    inputs:
      php_version:
        description: PHP version with which the scripts are executed
        default: "8.3"
        required: false
        type: string
      extensions:
        description: Setup php extension to use
        default: intl, bcmath, curl, openssl, mbstring, pdo_pgsql
        type: string
        required: false
      pre_run:
        description: Pre run script
        default: "./vendor/bin/phpunit --version"
        type: string
        required: false

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ inputs.php_version }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          extensions: ${{ inputs.extensions }}
          ini-values: memory_limit=-1
          coverage: pcov

      - name: Get composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Update project dependencies
        run: |
          composer update --no-interaction --no-progress --ansi

      - name: Runs pre run scripts
        run: ${{ inputs.pre_run }}

      - name: Runs phpunit tests
        run: ./vendor/bin/phpunit --colors
